// Farg'ona tumani mahallalari (MFY ro'yxati)
// Platforma faqat Farg'ona tumani hokimligi uchun ishlaydi.

export const FARGONA_TUMAN_NAME = "Farg'ona tumani";

export const FARGONA_TUMAN_MAHALLAS: string[] = [
  "Shohimardon",
  "Yordon",
  "Vodil",
  "Xo'ja Ahmad Vale",
  "Sanoat",
  "Hosilot",
  "Tinchlik",
  "Beruniy",
  "Bo'ston",
  "Marg'ilon",
  "Dilkusho",
  "Yambaroq",
  "Novkent",
  "Yuksalish",
  "Toshqo'rg'on Aziz",
  "Shohimardonobod",
  "Kaptarxona",
  "Yoyilma",
  "Mehnatobod",
  "Barqaror hamjixatlik",
  "Mindonobod",
  "Yangi asr",
  "Damko'l",
  "Bo'stonobod",
  "Guliston",
  "Oqtom",
  "Yuqori Vodil",
  "Navro'z",
  "Obod",
  "Log'on",
  "Vaziyo",
  "Xurshidi Tobon",
  "Gulpiyon",
  "Mash'al",
  "Avval",
  "Birdamlik",
  "Mozortagi",
  "Qorasuv",
  "O'rta qishloq",
  "Oqtepa",
  "Soy bo'yi",
  "Qo'riq",
  "Pastki Archa",
  "Yuqori Archa",
  "Chimyon",
  "Bahor",
  "Ulug'bek",
  "Langar",
  "Qurilish",
  "Zilol",
  "Shifokor",
  "Do'stlik",
  "Gulshan",
  "Dehqonobod",
  "Boy",
  "Yuqori Gulshan",
  "Mindon",
  "Markaz",
  "Guzar",
  "Xo'roba",
  "Sharq haqiqati",
  "Xonqiz",
  "Oq oltin",
  "O'zbekiston",
  "Farg'ona",
  "Qo'rg'ontepa",
  "Maydon",
  "Yangi yo'l",
  "Satkak",
  "Oqbilol",
  "Konchilar",
];

// Backwards-compat exports (used by older components/pages).
export const FARGONA_DISTRICTS = [
  { id: "fargona_tuman", name: FARGONA_TUMAN_NAME, mahallas: FARGONA_TUMAN_MAHALLAS },
];
